Update Status_check.yml

diff --git a/.github/workflows/Status_check.yml b/.github/workflows/Status_check.yml
--- a/.github/workflows/Status_check.yml
+++ b/.github/workflows/Status_check.yml
@@ -1,29 +1,32 @@
 name: Status Check Functions
 on: [push]
 
-jobs: 
+jobs:
   job-1:
     runs-on: ubuntu-latest
     steps:
-      - name: Step1
+      - name: Step 1
         run: sleep 20
+      - name: Step 2
+        id: step-2
+        run: exit 1
       - name: Runs on Failure
-        if: failure()
-        run: echo " Runs only on failuer"
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
       - name: Runs on Success
+        # This is not needed (DEFAULT BEAHAVIOUR)
         if: success()
         run: echo 'Runs on Success'
       - name: Always Runs
+        # if: success() || failure()
         if: always()
         run: echo 'Always Runs'
-      - name: Runs when cancelled 
+      - name: Runs When Cancelled
         if: cancelled()
-        
+        run: echo 'Runs on Cancelled'
   job-2:
     runs-on: ubuntu-latest
     needs: job-1
-    if: failuer()
+    if: failure()
     steps:
-      - run: echo 'Job2'
-
-    
+      - run: echo 'Job 2'
